# Generated by Django 5.0.3 on 2024-11-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemonAPI', '0002_category_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
    ]
